fieldLayouts:
  e1bb556d-0e4c-492c-ae4b-59d24394e177:
    tabs:
      -
        elements:
          -
            fieldUid: 441005c5-f52f-4dd8-8595-4fbe2049ddf0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: siteSettings
name: 'Site Settings'
